# Generated by Django 4.1.7 on 2023-04-08 00:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="moneymanage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("stockName", models.CharField(max_length=100)),
                (
                    "sharePriceBought",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("numberOfShares", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "dividendAmount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "dividendPercentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "shareBoughtDate",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
