# Generated by Django 4.1.7 on 2023-04-08 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stockmanage", "0002_rename_moneymanage_stockmanage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmanage",
            name="stockName",
        ),
    ]
