# Generated by Django 4.1.7 on 2023-04-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="indexetfmanage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indexName", models.CharField(max_length=10)),
                ("fundType", models.CharField(max_length=10)),
            ],
        ),
    ]
