# Generated by Django 4.1.7 on 2023-04-02 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="moneymanage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cashName", models.CharField(max_length=50)),
                ("cashType", models.CharField(max_length=50)),
                ("cashAmount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("cashRate", models.DecimalField(decimal_places=2, max_digits=6)),
                ("cashStartDate", models.DateField(default=django.utils.timezone.now)),
                (
                    "cashMaturityDate",
                    models.DateField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
